# Generated by Django 3.1.7 on 2021-05-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeuser',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
