# Generated by Django 3.1.7 on 2021-05-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_collegeuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeuser',
            name='nirfRanking',
            field=models.IntegerField(default=0),
        ),
    ]
