# Generated by Django 3.1.7 on 2021-05-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0004_collegeuser_is_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='totalLikes',
            field=models.IntegerField(default=0),
        ),
    ]
