# Generated by Django 3.1.7 on 2021-05-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0005_images_totallikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegeuser',
            old_name='location',
            new_name='city',
        ),
    ]
