# Generated by Django 3.1.7 on 2021-05-08 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0006_auto_20210508_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('citiId', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=200)),
                ('nearCity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collegeapp.cities')),
            ],
        ),
    ]
