# Generated by Django 3.1.7 on 2021-05-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0010_imagelikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
