# Generated by Django 3.1.7 on 2021-05-13 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0011_studentuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='nearCity',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='collegeapp.cities'),
        ),
    ]
