# Generated by Django 3.1.7 on 2021-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0012_auto_20210513_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
