# Generated by Django 3.1.7 on 2021-05-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0013_studentuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='url',
            field=models.URLField(default='', null=True),
        ),
    ]
