# Generated by Django 3.1.7 on 2021-05-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0015_auto_20210516_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegereview',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='collegereview',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='coursereview',
            name='userId',
        ),
        migrations.AddField(
            model_name='collegereview',
            name='collegeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.collegeuser'),
        ),
        migrations.AddField(
            model_name='collegereview',
            name='studentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.studentuser'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='studentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.studentuser'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='courseId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.collegecourses'),
        ),
    ]
