# Generated by Django 3.1.7 on 2021-05-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0016_auto_20210516_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='collegeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.collegeuser'),
        ),
    ]
