# Generated by Django 3.1.7 on 2021-05-17 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0019_auto_20210517_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='prefInstitute',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='profileWebsite',
        ),
    ]
