# Generated by Django 3.1.7 on 2021-05-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0020_auto_20210517_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
