# Generated by Django 3.1.7 on 2021-05-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0021_studentuser_is_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeuser',
            name='totalRating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
