# Generated by Django 3.1.7 on 2021-05-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0022_collegeuser_totalrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeuser',
            name='curriculumRating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='collegeuser',
            name='staffRating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='collegeuser',
            name='totalCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collegeuser',
            name='totalSum',
            field=models.IntegerField(default=0),
        ),
    ]
