# Generated by Django 3.1.7 on 2021-05-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0023_auto_20210518_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeuser',
            name='campusSum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collegeuser',
            name='collegeReviewCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collegeuser',
            name='courseReviewCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collegeuser',
            name='curriculumSum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collegeuser',
            name='librarySum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collegeuser',
            name='staffSum',
            field=models.IntegerField(default=0),
        ),
    ]
