# Generated by Django 3.1.7 on 2021-05-22 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0025_auto_20210519_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 17, 4, 50, 199368)),
        ),
    ]
