# Generated by Django 3.1.7 on 2021-05-22 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0026_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 17, 5, 50, 515254)),
        ),
    ]
