# Generated by Django 3.1.7 on 2021-05-22 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0027_auto_20210522_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 17, 6, 13, 705391)),
        ),
    ]
