# Generated by Django 3.1.7 on 2021-05-22 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0028_auto_20210522_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 17, 21, 9, 882886)),
        ),
    ]
