# Generated by Django 3.1.7 on 2021-05-22 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0031_auto_20210522_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformstatistics',
            old_name='totalReviews',
            new_name='totalCourses',
        ),
    ]
