# Generated by Django 3.1.7 on 2021-05-23 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collegeapp', '0032_auto_20210522_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursehelpful',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeapp.coursereview')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='collegehelpful',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeapp.collegereview')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
