# Generated by Django 3.1.7 on 2021-05-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0035_auto_20210524_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursehelpful',
            name='purpose',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
