# Generated by Django 3.1.7 on 2021-05-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0036_auto_20210524_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursereview',
            old_name='nothelpfulCount',
            new_name='notHelpfulCount',
        ),
        migrations.AddField(
            model_name='collegereview',
            name='notHelpfulCount',
            field=models.IntegerField(default=0),
        ),
    ]
